
[general]

	[general.chat]
		"color_for_chat_messages_(usernames)" = "_rank_ _name_ > _message_"
		toggle_custom_chat = false
		toggle_useless_chat_messages = false

	[general.render]
		toggle_other_users = true

[slayers]

	[slayers.message]
		slayer_rng_message = "&r&l_rarity_! &r&7(&e_drop_&7)&r &b(+_mf_ Magic Find!)"
		soulcry_alert = false

[other]

	[other.discord]
		rpc_toggle = true
		rpc_message = "Example RPC message"
		rpc_image = "sse_1024"

	[other.world_load]
		join_message = true

	[other.api]
		api_key = ""

	[other.displays]
		better_scoreboard = true

[displays]

	[displays.render]
		toggle_health_bar = true
		toggle_food_bar = true
		toggle_armor_bar = true
		toggle_xp_bar = true

[qol]

	[qol.better_term]
		better_term = true
		better_term_with_anything = true

	[qol.use_at_your_own_risk]
		anti_kb = true

