
[general]

	[general.chat]
		"color_for_chat_messages_(usernames)" = ""
		toggle_custom_chat = false
		toggle_useless_chat_messages = false

	[general.render]
		toggle_other_users = true

[slayers]

	[slayers.message]
		slayer_rng_message = ""
		soulcry_alert = false

[other]

	[other.on_game_open]
		auto_join_skysim = true

	[other.discord]
		rpc_toggle = true
		rpc_message = "coding is fun"
		rpc_image = ""

	[other.world_load]
		join_message = true

	[other.api]
		api_key = "76543db3-e993-4b2f-acb1-d964d6844a21:dGQEcHNxcF9nDA=="

	[other.displays]
		better_scoreboard = true

[displays]

	[displays.render]
		toggle_health_bar = true
		toggle_food_bar = true
		toggle_armor_bar = true
		displays = true
		toggle_xp_bar = true

[qol]

	[qol.better_term]
		better_term_delay = 2
		better_term = true
		better_term_with_anything = false

	[qol.use_at_your_own_risk]
		anti_kb = false

